### ISSUE TITLE
Intermittent page not found errors from AO search

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3270]
This issue originally reported by NewRelic alert system.  NewRelic is pinging the URL (https://www.fec.gov/data/legal/advisory-opinions/2018-08/) every 30 min from different part of the country.  Occasionally  `AO 2018-08`  is not returned therefore we are presented with `Page not found` message screen.  We can reproduce this error if you access the above URL right after you received the alert email.  If you refresh the page couple of times page will show up.

![image](https://user-images.githubusercontent.com/20324717/42458079-25cb68ae-8367-11e8-9e03-3e52359d24c1.png)

![image](https://user-images.githubusercontent.com/20324717/42458119-3fcb4d82-8367-11e8-8b7b-ec1f54e0f466.png)

This error also can be found in Kibana

July 8th 2018, 21:24:30.059   - 404 GET /data/legal/advisory-opinions/2018-08/ (10253.221 ms)
July 8th 2018, 21:24:30.056  -  404 GET /data/legal/advisory-opinions/2018-08/ (10239.801 ms)
July 8th 2018, 20:42:33.537 - 404 GET /data/legal/advisory-opinions/2018-08/ (10259.113 ms)
July 7th 2018, 23:25:03.407  -  404 GET /data/legal/advisory-opinions/2018-01/ (10234.212 ms)
July 7th 2018, 20:03:54.124  -  404 GET /data/legal/advisory-opinions/2018-01/ (10255.1 ms)

**Comment by vrajmohan** [comment]
I have been able to isolate the issue to the API layer and reproduce it on `dev` and `stage` as well with:
```
curl -v "https://fec-dev-api.app.cloud.gov/v1/legal/docs/advisory_opinions/2016-08"
curl -v "https://api-stage.open.fec.gov/v1/legal/docs/advisory_opinions/2016-08?API_KEY=DEMO_KEY"

```

**Comment by vrajmohan** [comment]
With the removal of S3 caching from `dev` and `stage`, we have better visibility into the root cause of the error.  The API fails with:
```
  2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR Traceback (most recent call last):                                                                                                  2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request                 2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     six.raise_from(e, None)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "<string>", line 2, in raise_from
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request                 2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     httplib_response = conn.getresponse()
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/newrelic/hooks/external_httplib.py", line 75, in httplib_getresponse_wrapper
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     return wrapped(*args, **kwargs)                                                                                                 2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/http/client.py", line 1331, in getresponse
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     response.begin()                                                                                                                2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/http/client.py", line 297, in begin
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     version, status, reason = self._read_status()                                                                                   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/http/client.py", line 258, in _read_status
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                                                                        2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/socket.py", line 586, in readinto                                                    2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     return self._sock.recv_into(b)                                                                                                  2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gevent/_socket3.py", line 384, in recv_into
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     self._wait(self._read_event)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gevent/_socket3.py", line 156, in _wait
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     self.hub.wait(watcher)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gevent/hub.py", line 651, in wait                                      2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     result = waiter.get()
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gevent/hub.py", line 898, in get                                       2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     return self.hub.switch()                                                                                                        2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     return RawGreenlet.switch(self)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR socket.timeout: timed out                                                                                                           2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR During handling of the above exception, another exception occurred:
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR Traceback (most recent call last):                                                                                                  2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen                       2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     _stacktrace=sys.exc_info()[2])                                                                                                  2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/util/retry.py", line 333, in increment
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     raise six.reraise(type(error), error, _stacktrace)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise                         2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     raise value
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     chunked=chunked)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/newrelic/hooks/external_urllib3.py", line 21, in _nr_wrapper_make_re
quest_
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     return wrapped(*args, **kwargs)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
   2018-07-10T13:28:53.21-0700 [APP/PROC/WEB/0] ERR urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='xfb49b66d97fb4.service.kubernetes', port=32658): Read timed out. (r
ead timeout=10)
```

**Comment by vrajmohan** [comment]
The root cause appears to be Elasticsearch timeouts. We should confirm this using `locust`.

**Comment by pkfec** [comment]
@vrajmohan 
I tried to run the locust test in both **dev** and **stage** environments.

for **stage** i input this URL : 
locust --host=https://apistage.open.fec.gov/v1/legal/docs/advisory_opinions/2016-08.

after running the locust, URL has candidates appended at the end(second screen shot). Screen shots attached below. Not sure if this is right. 

<img width="878" alt="screen shot 2018-07-10 at 9 55 54 pm" src="https://user-images.githubusercontent.com/11650355/42546672-5ab89fe8-848c-11e8-83be-29169320e550.png">
<img width="1231" alt="screen shot 2018-07-10 at 9 57 19 pm" src="https://user-images.githubusercontent.com/11650355/42546678-5f2bc438-848c-11e8-8518-3c213f8d9e0a.png">

**Comment by vrajmohan** [comment]
Try `locust --host=https://api-stage.open.fec.gov/v1/`

**Comment by pkfec** [comment]
I thought we are only hitting the legal part of api. The above URL will mislead results, cause it is checking both legal and other endpoints as well.

**Comment by vrajmohan** [comment]
We are using Locust to be able to reproduce the error easily. The results are in any case reported separately for different endpoints.

**Comment by pkfec** [comment]
- Read Locust documentation (from set up to analyzing the logs, how to add weight to an endpoint etc... )
- Read ES-56 documentation on  when and why the  timeouts happen and how to tweak it.
- Run Locust against ES-56 locally and triage timeouts as needed .

**Comment by pkfec** [comment]
Ran the locust test against my local instance of ES56. Screenshot attached below.
- loaded  AO's 2018-01 thru 2018-10 
- got my local ES server up
- ran locust test 
- unable to reproduce in my local
<img width="1238" alt="screen shot 2018-07-13 at 4 04 15 pm" src="https://user-images.githubusercontent.com/11650355/42712464-c6780e92-86b9-11e8-9fe0-1100b8e03e95.png">

**Comment by vrajmohan** [comment]
We should also test with Elasticsearch 2.x to see if the performance is any better. @fec-jli, @lbeaufort, @pkfec: do we have the results of the Locust tests when we originally migrated from 2.x to 5.x?

**Comment by pkfec** [comment]
Last friday, i ran the locust test against dev api. Screen shots attached below.
<img width="1271" alt="screen shot 2018-07-16 at 1 08 18 pm" src="https://user-images.githubusercontent.com/11650355/42773116-4e1c0a14-88fa-11e8-89d9-b95d0148dc8a.png">
<img width="1273" alt="screen shot 2018-07-16 at 1 08 27 pm" src="https://user-images.githubusercontent.com/11650355/42773124-5373d488-88fa-11e8-8d30-a81e30d95393.png">

dev api on ES56. There are few instances that the request timed out.

**Comment by pkfec** [comment]
@vrajmohan i do not recall myself running the locust test before switching to the new ES56 service.

**Comment by pkfec** [comment]
@vrajmohan should we reach out to  cloud.gov team and  see if something changed in past 2 weeks on ES56?

**Comment by lbeaufort** [comment]
@pkfec @vrajmohan I think these are the locust test results you're looking for: https://drive.google.com/drive/folders/1F4lFVVC6gFfN7rwhfNl41WvhUBkksimp?ths=true

**Comment by vrajmohan** [comment]
Screenshots attached to the issue and spreadsheets saved in Google Drive make it difficult to compare. Please collate all your results in a single table so that it is easy to compare.

**Comment by vrajmohan** [comment]
Once we have this compiled, we can file an issue with cloud.gov.

**Comment by pkfec** [comment]
reached out  to  **cloud.gov support**  team. 
CC'ed you all on the email that i sent to cloud.gov support team : @vrajmohan @lbeaufort @rjayasekera and @jwchumley

**Comment by vrajmohan** [comment]
@rjayasekera, can you find out (as much as possible) when exactly these timeouts started happening? I am confused because that information is muddled by the changes to the NewRelic alerts.

@pkfec, can you also run these tests after increasing the `timeout` on the Elasticsearch connection?

**Comment by pkfec** [comment]
I did not see any 500 errors when the timeouts are bumped to 20s. I have uploaded the results here:
https://drive.google.com/drive/folders/1F4lFVVC6gFfN7rwhfNl41WvhUBkksimp?ths=true

**Comment by pkfec** [comment]
1.  Load the latest entire snapshot to your  local environment. And and run the locust test against it to make sure there are no timeouts. 
NOTE : I have loaded subset of AO data and ran the locust test. But we want to load the entire dataset and run the tests.

2. Create an  new index with a smaller subset of data and run the locust test to see if we can replicate the timeouts/slowness.

3. Use curl command to  retrieve a specific AO on a elastic search service:
-  open a connection to elasticsearch via ssh `cf ssh api`
-  get URI for ES with `cf env api`
-  query with `curl -v GET "<URI>/docs/advisory_opinions/2018-02" | python -m json.tool | less`

**Comment by pkfec** [comment]
I have run locust test in `dev` space by increasing the timeouts to 20s. There were no time out errors. Uploaded the results here:
https://docs.google.com/spreadsheets/d/176GslTcBtvxMUBM6PK3XaH1ZRdDJ3RQOwtOTOzICji8/edit#gid=0.

I am going to load all legal docs to my local and test to see if i can reproduce any ES56 timeouts.

**Comment by lbeaufort** [comment]
@pkfec after re-reading the email from cloud.gov, we want to decrease the timeout rather than increase it so it tries more often:

`es = Elasticsearch(timeout=5, max_retries=5, retry_on_timeout=True)`

**Comment by lbeaufort** [comment]
We are waiting to hear back from an email we sent to cloud.gov with some questions we had on continued timeout/slowness issues.

**Comment by lbeaufort** [comment]
Update: cloud.gov has identified a configuration issue on their end and are working on a solution. Once they have tested and rolled it out, no changes need to be made on our end. We should locust test with our old and new connection settings to measure which has better performance.

**Comment by lbeaufort** [comment]
Cloud.gov fixed a configuration issue on their end - we [tested it and found much better results](https://docs.google.com/spreadsheets/d/176GslTcBtvxMUBM6PK3XaH1ZRdDJ3RQOwtOTOzICji8/edit#gid=0).

A hotfix was pushed to reset connection defaults so MUR 253 will load.
