### ISSUE TITLE
upgrade Flask and Flask-related modules to the newest version

### ISSUE THREAD

**Issue by qqss88** [fecgov/openFEC#3371]
Since our flask library is behind, we need to upgrade to the latest major version. This will also require more testing by all the devs since this is a major upgrade.

Flask==1.02
Flask-Cors==3.0.6
Flask-Script==2.0.6
Flask-RESTful==0.3.6
Flask-SQLAlchemy==2.3

**Completion Criteria:**
- [x] Check vulnerabilities
- [x] Check compatability
- [x] Make a separate testing ticket to have other devs check the application

**Comment by qqss88** [comment]
will also include newrelic==2.106.0.87 upgrade for potential security issues based on research from #3344.

**Comment by qqss88** [comment]
check for more out-dated packages:

pipenv update --outdated
Package 'Flask-SQLAlchemy' out-of-date: '==2.3.0' installed, '==2.3' available.
Package 'marshmallow-sqlalchemy' out-of-date: '==0.4.1' installed, '==0.8.0' available.

**Comment by qqss88** [comment]
Flask-SQLAlchemy will be updated to 2.3.1, which is the current stable version.

**Comment by qqss88** [comment]
Upgrading Flask-SQLALchemy to >=2.2 will fail launching pyest - need to dig a little more on this:


Traceback (most recent call last):
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/_pytest/config/__init__.py", line 377, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/sunshine168/workspace/FEC/openFEC-develop/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/_pytest/config/__init__.py", line 408, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/sunshine168/workspace/FEC/openFEC-develop/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/_pytest/config/__init__.py", line 414, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 235, in load_module
    six.exec_(co, mod.__dict__)
  File "/Users/sunshine168/workspace/FEC/openFEC-develop/tests/conftest.py", line 1, in <module>
    import manage
  File "/Users/sunshine168/workspace/FEC/openFEC-develop/manage.py", line 14, in <module>
    from webservices.common import models
  File "/Users/sunshine168/workspace/FEC/openFEC-develop/webservices/common/models/__init__.py", line 1, in <module>
    from .base import db  # noqa
  File "/Users/sunshine168/workspace/FEC/openFEC-develop/webservices/common/models/base.py", line 56, in <module>
    db = RoutingSQLAlchemy()
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 745, in __init__
    self.session = self.create_scoped_session(session_options)
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 780, in create_scoped_session
    self.create_session(options), scopefunc=scopefunc
  File "/Users/sunshine168/workspace/FEC/openFEC-develop/webservices/common/models/base.py", line 53, in create_session
    return RoutingSession(self, **options)
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 143, in __init__
    self.app = app = db.get_app()
  File "/Users/sunshine168/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 953, in get_app
    if self.app is not None:
AttributeError: 'RoutingSQLAlchemy' object has no attribute 'app'
ERROR: could not load /Users/sunshine168/workspace/FEC/openFEC-develop/tests/conftest.py

**Comment by qqss88** [comment]
upgrade Flask-Cors:
pip install Flask-Cors==3.0.6

all unit tests passed.

**Comment by qqss88** [comment]
upgrade Flask-RESTful:
pip install Flask-RESTful==0.3.6

all unit tests passed.

**Comment by qqss88** [comment]
upgrade newrelic:
pip install newrelic==2.106.0.87

all unit tests passed.

**Comment by vrajmohan** [comment]
@qqss88, is your branch available for us to look at?

**Comment by qqss88** [comment]
![image](https://user-images.githubusercontent.com/7330555/45791196-9a7ea300-bc56-11e8-8e62-7e20b5071017.png)

**Comment by qqss88** [comment]
the above piece of code change from 2.1 to 2.2 will break the way we use flask-sqlalchemy: create_session failed.

**Comment by qqss88** [comment]
creat_session implementation is different from 2.1 to 2.2:

![image](https://user-images.githubusercontent.com/7330555/45882707-f6dbe280-bd7c-11e8-9cb8-51f42ed3a9e1.png)

**Comment by qqss88** [comment]
An easy solution to modify our own create_session function:

return RoutingSession(self, **options) -->
return orm.sessionmaker(class_=RoutingSession, db=self, **options)

**Comment by qqss88** [comment]
another solution is to build a sqlalchemy-specific db for pytest only. 

based on my testing, both solutions fix unit tests.

**Comment by AmyKort** [comment]
fecgov/openFEC#3403  is merged, so closing.
