### ISSUE TITLE
Server error for loading page 2 of MUR results

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3985]
For [this search](https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=%22foreign+national%22+AND+%22ssf%22&case_no=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=), when you try to get to page 2, you get the error:

![Screen Shot 2019-10-02 at 10 47 10 AM](https://user-images.githubusercontent.com/31420082/66054471-077f7680-e502-11e9-8c91-a54b23e101e9.png)

This is because of the API call failing: https://fec-dev-api.app.cloud.gov/v1/legal/search?hits_returned=20&type=murs&from_hit=20&q=%22foreign+national%22+AND+%22ssf%22

Full stack trace, partially redacted:
```
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT WARNING:elasticsearch:GET http://*****.service.kubernetes:*****/docs_search/_search [status:N/A request:10.007s]
   2019-10-02T10:40:34.86-0400 [RTR/2] OUT fec-dev-api.app.cloud.gov - [2019-10-02T14:40:24.826+0000] "GET /v1/legal/search?hits_returned=20&type=murs&from_hit=20&q=%22foreign+national%22+AND+%22ssf%22 HTTP/1.1" 500 0 51 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" "127.0.0.1:51138" "10.10.2.12:61090" x_forwarded_for:"65.132.39.244, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"5ce955af-b430-49c5-6470-cf6e542245c8" response_time:10.034737861 app_id:"4e0f8a20-6cc2-4711-bad9-44160baf19f8" app_index:"0" x_b3_traceid:"a2a53cdcff0abbc5" x_b3_spanid:"a2a53cdcff0abbc5" x_b3_parentspanid:"-" b3:"a2a53cdcff0abbc5-a2a53cdcff0abbc5"
   2019-10-02T10:40:34.86-0400 [RTR/2] OUT 
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT Traceback (most recent call last):
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     six.raise_from(e, None)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "<string>", line 2, in raise_from
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     httplib_response = conn.getresponse()
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/http/client.py", line 1336, in getresponse
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     response.begin()
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/http/client.py", line 306, in begin
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     version, status, reason = self._read_status()
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/http/client.py", line 267, in _read_status
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/socket.py", line 589, in readinto
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     return self._sock.recv_into(b)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/gevent/_socket3.py", line 433, in recv_into
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     self._wait(self._read_event)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_hub_primitives.py", line 284, in gevent.__hub_primitives.wait_on_socket
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_hub_primitives.py", line 289, in gevent.__hub_primitives.wait_on_socket
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_hub_primitives.py", line 280, in gevent.__hub_primitives._primitive_wait
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_hub_primitives.py", line 281, in gevent.__hub_primitives._primitive_wait
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT socket.timeout: timed out
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT During handling of the above exception, another exception occurred:
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT Traceback (most recent call last):
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     _stacktrace=sys.exc_info()[2])
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/util/retry.py", line 344, in increment
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     raise six.reraise(type(error), error, _stacktrace)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     raise value
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     chunked=chunked)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='*****.service.kubernetes', port=*****): Read timed out. (read timeout=10)
   2019-10-02T10:40:34.85-0400 [APP/PROC/WEB/0] OUT ERROR:webservices.resources.legal:('TIMEOUT', "HTTPConnectionPool(host='*****.service.kubernetes', port=*****): Read timed out. (read timeout=10)", ReadTimeoutError("HTTPConnectionPool(host='*****.service.kubernetes', port=*****): Read timed out. (read timeout=10)"))
   2019-10-02T10:40:34.86-0400 [APP/PROC/WEB/0] OUT 127.0.0.1 - - [02/Oct/2019:14:40:34 +0000] "GET /v1/legal/search?hits_returned=20&type=murs&from_hit=20&q=%22foreign+national%22+AND+%22ssf%22 HTTP/1.1" 500 51 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
```

**Comment by lbeaufort** [comment]
- Consider looking into workarounds until this is fixed
- Examine the scope of this issue
