### ISSUE TITLE
Configuration checking crashes the application intermittently

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4162]
We had a ~30 minute outage on 1/29/20 due to the application crashing with error message `RuntimeError: Invalid configuration: [[], ['elasticsearch24'], []]`.

The missing `elasticsearch24` service can't be the entire problem though, otherwise the build would always fail (a rebuild brought the app back up)

Complete error message:

```
  2020-01-29T13:25:25.50-0500 [APP/PROC/WEB/7] OUT Missing services redis32, s3, elasticsearch24
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR Traceback (most recent call last):
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR   File "manage.py", line 182, in <module>
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR     manager.run()
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR     result = self.handle(argv[0], argv[1:])
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR     res = handle(*args, **config)
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR     return self.run(*args, **kwargs)
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR   File "manage.py", line 164, in cf_startup
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR     check_config()
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR   File "/home/vcap/app/webservices/config.py", line 66, in check_config
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR     raise RuntimeError('Invalid configuration: {0}'.format(results))
   2020-01-29T13:25:25.58-0500 [APP/PROC/WEB/7] ERR RuntimeError: Invalid configuration: [[], ['elasticsearch24'], []]
```

Kibana logs indicate this errors message starting happening on July 11, 2019: https://logs.fr.cloud.gov/goto/1a8e5b6d064f698053997b648fc18aec

- [ ] Figure out how to replicate the issue
- [ ] Test a fix
- [ ] Hold a post-mortem on outage

**Comment by lbeaufort** [comment]
Update - I'm not able to replicate the outage, but it's best to update the elasticsearch version, which will reduce the chances of issues. After digging through the logs, the outage on January 29th wasn't caused by this issue, though it could have been exacerbated by it. 502 errors stopped happening about 5 minutes before the redeploy. 

I'm guessing there was some sort of replica lag after we made changes to a view that is the underlying logic for a lot of the API: https://github.com/fecgov/openFEC/pull/4154/files. I think we should still move forward with fixing this configuration check and consider fixing headless Flyway apps so we can run big migrations off-hours. We may want to consider doing deploys with changes to essential tables off-hours until we can figure out why this has been causing 502 errors.
