### ISSUE TITLE
upgrade to Elasticsearch v7.4 beta service

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#4505]
The cloud.gov team is launching a beta of a new Elasticsearch service using AWS Elasticache. Upgrade API to the new beta service and test the legal services section of the website. 

**Note: Not backwards compatible to previous versions. Cannot load a 5.6 into a 7.4 version. This is a blocker for our migration.**

Related issue https://github.com/fecgov/openFEC/issues/2921

**Action items:**
- [x] Create a new ES7.4 High Availability beta service on `feature` space.
- [x] Set up API app on `feature` space.
- [x] Setup circleci env variable and deploy api on feature space successfully.
- [x] Refactor all mappings to match the new ES7 service (docs, archived_mur indexes).
- [x] Add new ES client connection function using AWS4Auth and test the ES connection.
- [x] Upload all legal docs to `feature` space.(AO, ADR, AF, MUR, Archived MURs, Statues, Regulations)
- [x] Refactor  existing index_management.py and move all the manage functions into the new file es_management.py.
- [x] Create new manage command (check_legal_doc) to view the legal data on the ES service.
- [x] Create a public S3 bucket service (fec-s3-api) to save legal pdf file. 
- [x] Configure the public S3 bucket to list the object in a browser (cloud.gov put the listobject policy  on this new bucket)
- [x] Create a new private s3 bucket service (fec-s3-snapshot) to save ES snapshot.(separated from public s3 bucket)
- [x] Config ES7 repository and  test snapshots 
- [x] Clean OCR text data on the **arch-mur253**(with 8 documents), which fixed the **Message: Request size exceeded 10485760 bytes** error while loading to ES7 service.
- [x] Refactor the **legal/search** and **legal/docs** api endpoints.
- [x] Integrate CMS and API and test the legal search.
- [x] Refactor all schedule task code.
- [x] Refactor and test downloads.
- [x] Refactor pytests.
- [x] Refactor and test snapshot and restore.
- [x] Refactor all management commands.
- [x] Conduct performance test (load test).

**Completion criteria:**
- [ ] Cloud.gov is flagged about backwards compatibility problems
- [ ] Identify the migration path from 5.6 to 7.4

**Future work:**
- Our legal search is able to run on elasticsearch v7.4 without degraded performance

**Comment by pkfec** [comment]
Here is the email we received from cloud.gov about the elasticsearch beta service plans:

> The cloud.gov team is pleased to announce the launch of a beta of a new Elasticsearch service using AWS Elasticache. This work is an important step in moving cloud.gov towards a more stable and reliable platform by moving away from a bespoke Kubernetes instances to AWS-hosted services. 
> 
> The intent of the Elasticsearch beta is to test out the service with a limited number of customers before making it available to all cloud.gov customers. 
> 
> We ask that interested customers email support@cloud.gov to request access to the beta and specify the org(s) in which they would like to enable the beta service. 
> 
> We’ve outlined below a few important things to keep in mind before and while you are using the beta.
> 
> The beta should only be used in non-production environments.
> For this beta, the cloud.gov operators will be limiting access to this new broker by specific organizations only. All spaces within an organization will have access to the beta.
> While we took every measure to test the broker before releasing it to beta, testing for performance is one area that is difficult to assess pre-release. Therefore, we will be closely monitoring performance once in beta, but we expect some performance work may be required early in the beta.
> The cloud.gov team will use the weekly office hours to solicit feedback from you about the beta.
> The cloud.gov team reserves the right to update and change the broker and plan details based on testing and feedback results.
> Elasticsearch instances created in beta testing will not be carried over into production once the service goes General Availability (GA).  Once GA is announced, the beta plans will be disabled from creating new instances and deleted a short time later. 
> Please submit any feedback or support requests about the Redis broker beta to support@cloud.gov.
> If you would like to participate in the beta, please contact support@cloud.gov to request access to the beta and specify the org(s) in which you would like to enable the beta service.
> 
> Technical Notes for the beta release:
> 
> The service name will simply be called aws-elasticsearch
> The elasticsearch offering will come in three plans:
> BETA-es-dev
> Single data only node
> Non-prod use only
> BETA-es-medium
> Three master nodes
> Two data nodes
> BETA-es-medium-ha
> Three master nodes
> Four data nodes
> All plans for Elasticsearch include the following:
> Elasticsearch version 7.4
> The system will automatically take snapshots hourly and will retain 336 of snapshots for up to 14 days.  NOTE: these snapshots can only be used for a cluster restore only.  Customers will need to perform manual snapshots if they want to backup their data for uses other than cluster restore.
> Data nodes will have 10G of usable disk
> This new offering will require customers to use AWS specific HTTP signing requests.  Please see the following for more details: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html
> Please note that the startup of Elasticsearch on AWS may be delayed. We’ve seen AWS take 5 mins per node and up to a couple hours for 2 nodes. 
> If customers have successful code changes in various languages that they would like to share examples of with other cloud.gov customers, we encourage PRs to our example repo: https://github.com/cloud-gov/aws-elasticsearch-example
>  
> --
> Kara Reinsel
> Product Manager - cloud.gov

**Comment by pkfec** [comment]
Test Elasticsearch 7.4 service on local env:

1. Download Elasticsearch 7.4 from here: 

     - https://www.elastic.co/downloads/past-releases/elasticsearch-7-4-0

2. Tried to start the ES74 server and ran into OS related errors:
Error stack trace on the terminal :
```
Caused by: org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory.

Error stack trace:
[2020-08-11T21:49:30,518][INFO ][o.e.x.s.a.s.FileRolesStore] [macadmins-mbp-5.lan] parsed [0] roles from file [/Users/pkasireddy/Projects/elasticsearch-7.4.0/config/roles.yml]
[2020-08-11T21:49:42,694][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [macadmins-mbp-5.lan] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.4.0.jar:7.4.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.4.0.jar:7.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.4.0.jar:7.4.0]
Caused by: org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:524) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:450) ~[elasticsearch-7.4.0.jar:7.4.0]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_171]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_171]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_171]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_171]
	at org.elasticsearch.node.Node.<init>(Node.java:453) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.4.0.jar:7.4.0]
	... 6 more

```

3. Check my current Java version:
```
macadmins-mbp-5:~ pkasireddy$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

4. The latest elasticsearch 7.* and JDK 1.8 are incompatible. To start elasticsearch v7.* JDK 11 or higher is required. 
Ran `brew update` and `brew upgrade` commands which  installed the JDK14.

**Comment by pkfec** [comment]
mapping type(s)  disabled in ES7.*. Tried creating a sample students index  on my local ES74 service.

curl -XPOST 'http://localhost:9200/students/student' -H 'Content-Type: application/json' -d'
{
     "student": { 
       "properties": { 
         "name": "keyword",
         "degree": "keyword",
         "age": "integer"  
         }
     }
 }'

**Comment by fec-jli** [comment]
To do list:
1)revise test case;
2)modify “docs” mappings
3)adjust index_management.py to split separated files
4)revise backup/snapshot code;
5)revise s3 code for local, add try; check s3 on cloud
6)revise the legal api;
7)make sure frontend works;
8)modify other management commands ;
9)revise schedule task code.
10)…

**Comment by fec-jli** [comment]
09/24/2020 update:
finished:
1)Modify "mappings" and create new ES connection function with AWS4Auth, ES connection successfully.
2)upload all legal docs to ‘feature’ space successfully (except big arch-mur253 hit size limitation issue)
3)create es_management.py to put all manage functions in this file(separated from other upload code)
4)create new command: check_legal_doc to check all data on ES
5)create a public S3 bucket to save legal pdf file, config it to be viewed on browser successfully
6)setup circleci env variable and deploy api on feature space successfully
7)create a new private s3 bucket to save ES snapshot.(separated from public s3 bucket)
8)config ES snapshot successfully

to do list:
1)revise the legal api
2)make sure frontend works
3)revise schedule task code.
4)revise test case
5)make decision for big arch-mur253 pdf ocr text.

**Comment by pkfec** [comment]
Tracking all code changes in a WIP PR here  #https://github.com/fecgov/openFEC/pull/4596
