### ISSUE TITLE
Investigate celery worker errors "SSL connection has been closed unexpectedly"

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4539]
https://logs.fr.cloud.gov/goto/a187ef9b3630f2836b8c024bcb113476

Looks like this has been happening a lot more since 7/20/20:

<img width="1269" alt="Screen Shot 2020-08-05 at 2 13 18 PM" src="https://user-images.githubusercontent.com/31420082/89448595-de350580-d725-11ea-9428-7a946e993b39.png">

This has been causing some downloads to fail: 

```2020-08-05T14:03:13.89-0400 [APP/PROC/WEB/1] ERR [2020-08-05 18:03:13,895: INFO/MainProcess] Received task: webservices.tasks.download.export_query[79b5d03b-cad3-4031-801c-89afa942bcc2]  
   2020-08-05T14:03:13.89-0400 [APP/PROC/WEB/1] ERR [2020-08-05 18:03:13,896: INFO/ForkPoolWorker-3] Download query: b'sort_hide_null=false&sort_nulls_last=true&sort=-total_receipts&cycle=1992&election_full=true&duration=4&office=president'
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR [2020-08-05 18:03:13,922: ERROR/ForkPoolWorker-3] Download failed: b'sort_hide_null=false&sort_nulls_last=true&sort=-total_receipts&cycle=1992&election_full=true&duration=4&office=president'
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR Traceback (most recent call last):
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     cursor, statement, parameters, context
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     cursor.execute(statement, parameters)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR psycopg2.errors.AdminShutdown: terminating connection due to administrator command
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR SSL connection has been closed unexpectedly
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR The above exception was the direct cause of the following exception:
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR Traceback (most recent call last):
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/app/webservices/tasks/download.py", line 147, in export_query
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     resource = call_resource(path, qs)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/app/webservices/tasks/download.py", line 37, in call_resource
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     count, _ = counts.get_count(resource, query)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/app/webservices/common/counts.py", line 27, in get_count
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     rows = get_query_plan(query)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/app/webservices/common/counts.py", line 39, in get_query_plan
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     return models.db.session.execute(explain(query)).fetchall()
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     return getattr(self.registry(), name)(*args, **kwargs)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1268, in execute
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     clause, params or {}
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     return meth(self, multiparams, params)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     return connection._execute_clauseelement(self, multiparams, params)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     distilled_params,
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     e, statement, parameters, cursor, context
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     util.raise_from_cause(sqlalchemy_exception, exc_info)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     reraise(type(exception), exception, tb=exc_tb, cause=cause)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     raise value.with_traceback(tb)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     cursor, statement, parameters, context
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR     cursor.execute(statement, parameters)
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR SSL connection has been closed unexpectedly
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR [SQL: EXPLAIN SELECT DISTINCT anon_1.candidate_id AS anon_1_candidate_id, anon_1.candidate_election_year AS anon_1_candidate_election_year, anon_1.candidate_name AS anon_1_candidate_name, anon_1.party_full AS anon_1_party_full, anon_1.incumbent_challenge_full AS anon_1_incumbent_challenge_full, anon_1.office AS anon_1_office, anon_1.total_receipts AS anon_1_total_receipts, anon_1.total_disbursements AS anon_1_total_disbursements, anon_1.cash_on_hand_end_period AS anon_1_cash_on_hand_end_period, anon_1.committee_ids AS anon_1_committee_ids, anon_1.coverage_end_date AS anon_1_coverage_end_date, anon_1.candidate_pcc_id AS anon_1_candidate_pcc_id, ofec_committee_detail_mv.name AS candidate_pcc_name 
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR FROM (SELECT anon_2.candidate_id AS candidate_id, anon_2.candidate_election_year AS candidate_election_year, max(anon_2.candidate_name) AS candidate_name, max(anon_2.party_full) AS party_full, max(anon_2.incumbent_challenge_full) AS incumbent_challenge_full, max(anon_2.office) AS office, sum(coalesce(anon_2.receipts, %(coalesce_1)s)) AS total_receipts, sum(coalesce(anon_2.disbursements, %(coalesce_2)s)) AS total_disbursements, sum(coalesce(anon_2.last_cash_on_hand_end_period, %(coalesce_3)s)) AS cash_on_hand_end_period, array_agg(DISTINCT anon_2.committee_id) AS committee_ids, max(anon_2.coverage_end_date) AS coverage_end_date, max(anon_2.candidate_pcc_id) AS candidate_pcc_id 
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR FROM (SELECT anon_3.candidate_id AS candidate_id, anon_3.candidate_election_year AS candidate_election_year, anon_3.committee_id AS committee_id, max(anon_3.name) AS candidate_name, max(anon_3.party_full) AS party_full, max(anon_3.incumbent_challenge_full) AS incumbent_challenge_full, max(anon_3.office) AS office, sum(coalesce(anon_3.receipts, %(coalesce_4)s)) AS receipts, sum(coalesce(anon_3.disbursements, %(coalesce_5)s)) AS disbursements, max(coalesce(anon_3.last_cash_on_hand_end_period, %(coalesce_6)s)) AS last_cash_on_hand_end_period, max(anon_3.coverage_end_date) AS coverage_end_date, max(anon_3.candidate_pcc_id) AS candidate_pcc_id 
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR FROM (SELECT anon_4.candidate_id AS candidate_id, anon_4.name AS name, anon_4.party_full AS party_full, anon_4.incumbent_challenge_full AS incumbent_challenge_full, anon_4.office AS office, anon_4.two_year_period AS two_year_period, anon_4.candidate_election_year AS candidate_election_year, anon_4.committee_id AS committee_id, anon_4.receipts AS receipts, anon_4.disbursements AS disbursements, first_value(anon_4.last_cash_on_hand_end_period) OVER (PARTITION BY anon_4.candidate_id, anon_4.candidate_election_year, anon_4.committee_id ORDER BY CASE WHEN (anon_4.coverage_end_date IS NOT NULL) THEN anon_4.two_year_period END DESC NULLS LAST) AS last_cash_on_hand_end_period, first_value(anon_4.coverage_end_date) OVER (PARTITION BY anon_4.candidate_id, anon_4.candidate_election_year, anon_4.committee_id ORDER BY CASE WHEN (anon_4.coverage_end_date IS NOT NULL) THEN anon_4.two_year_period END DESC NULLS LAST) AS coverage_end_date, anon_4.candidate_pcc_id AS candidate_pcc_id 
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR FROM (SELECT DISTINCT ofec_candidate_history_mv.candidate_id AS candidate_id, ofec_candidate_history_mv.name AS name, ofec_candidate_history_mv.party_full AS party_full, ofec_candidate_history_mv.incumbent_challenge_full AS incumbent_challenge_full, ofec_candidate_history_mv.office AS office, ofec_candidate_history_mv.two_year_period AS two_year_period, ofec_cand_cmte_linkage_mv.election_yr_to_be_included AS candidate_election_year, ofec_cand_cmte_linkage_mv.cmte_id AS committee_id, ofec_totals_combined_vw.receipts AS receipts, ofec_totals_combined_vw.disbursements AS disbursements, ofec_totals_combined_vw.last_cash_on_hand_end_period AS last_cash_on_hand_end_period, ofec_totals_combined_vw.coverage_end_date AS coverage_end_date, CASE WHEN (ofec_cand_cmte_linkage_mv.cmte_dsgn = %(cmte_dsgn_1)s) THEN ofec_cand_cmte_linkage_mv.cmte_id END AS candidate_pcc_id 
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR FROM ofec_candidate_history_mv LEFT OUTER JOIN ofec_cand_cmte_linkage_mv ON ofec_candidate_history_mv.candidate_id = ofec_cand_cmte_linkage_mv.cand_id AND ofec_candidate_history_mv.two_year_period = ofec_cand_cmte_linkage_mv.fec_election_yr LEFT OUTER JOIN ofec_totals_combined_vw ON ofec_cand_cmte_linkage_mv.cmte_id = ofec_totals_combined_vw.committee_id AND ofec_cand_cmte_linkage_mv.fec_election_yr = ofec_totals_combined_vw.cycle AND ofec_cand_cmte_linkage_mv.cmte_dsgn IN (%(cmte_dsgn_2)s, %(cmte_dsgn_3)s) 
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR WHERE ofec_cand_cmte_linkage_mv.cmte_dsgn IN (%(cmte_dsgn_4)s, %(cmte_dsgn_5)s) AND ofec_candidate_history_mv.two_year_period <= %(two_year_period_1)s AND ofec_candidate_history_mv.two_year_period > %(two_year_period_2)s AND ofec_cand_cmte_linkage_mv.election_yr_to_be_included = %(election_yr_to_be_included_1)s AND ofec_candidate_history_mv.office = %(office_1)s AND ofec_candidate_history_mv.candidate_inactive = false) AS anon_4) AS anon_3 GROUP BY anon_3.candidate_id, anon_3.candidate_election_year, anon_3.committee_id) AS anon_2 GROUP BY anon_2.candidate_id, anon_2.candidate_election_year) AS anon_1 LEFT OUTER JOIN ofec_committee_detail_mv ON anon_1.candidate_pcc_id = ofec_committee_detail_mv.committee_id]
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR [parameters: {'coalesce_1': 0.0, 'coalesce_2': 0.0, 'coalesce_3': 0.0, 'coalesce_4': 0.0, 'coalesce_5': 0.0, 'coalesce_6': 0.0, 'cmte_dsgn_1': 'P', 'cmte_dsgn_2': 'P', 'cmte_dsgn_3': 'A', 'cmte_dsgn_4': 'P', 'cmte_dsgn_5': 'A', 'two_year_period_1': 1992, 'two_year_period_2': 1988, 'election_yr_to_be_included_1': 1992, 'office_1': 'P'}]
   2020-08-05T14:03:13.92-0400 [APP/PROC/WEB/1] ERR (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by lbeaufort** [comment]
It looks like we started getting these errors when we enabled automatic termination of long-running queries. I’m thinking there’s an issue with `celery-worker` keeping database connections open, but in the meantime, @dzhang-fec kindly disabled the automated terminations in `prod` and enabled them in `stage`  for further testing. I can run some locust tests to figure out if downloads are being terminated too early.

**Comment by dzhang-fec** [comment]
@lbeaufort , here is the updated logic for your review.  To kill the process. As we discussed we disabled it for the download query killing >10mins, We added the  lower(query) like '% limit %'   to not kill the download. 
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE  lower(query) like '% limit %' and datname <>'rdsadmin' and usename ='fec_api' and  (now() - pg_stat_activity.query_start) > interval '10 minutes' order by pg_stat_activity.query_start desc

**Comment by lbeaufort** [comment]
This error is no longer occurring in `prod` and we're seeing them on `stage`, so everything it set up to test further on `stage`. Alternately, we could de-prioritize further testing and implement the same logic on `stage` as it appears @dzhang-fec's changes addressed the issue.

**Comment by lbeaufort** [comment]
From @dzhang-fec 
>We have these enabled today in PROD and Stage for testing from today.
I'm sorry I missed this before - it looks like they're still happening occasionally in `stage` but it's no longer symptomatic so I think it's ok to close this issue for now.

**Comment by dzhang-fec** [comment]
We have enable the jobs from databse server. Yes, it is ok to close it.
