### ISSUE TITLE
Small queries being terminated sooner than 9 minutes 

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4835]
### What we’re after

Determine if queries are being terminated prematurely or too quickly given our connection pooling settings.

**Note:** The stage environment has less API applications running than in production. Therefore the stage environment may be more symptomatic when it comes to query termination.

### Action item(s)

- [ ] Understand and document how connection pooling is currently working for the API
- [ ] Check connection pooling settings to see if this is causing any issues
- [ ] Determine if connection pooling reuses PID, if yes then we are probably terminating queries we don't need to
- [ ] Check previous releases from 4/27/2021 to see if something may have been introduced to cause these issues

### Completion criteria

- [ ] Based on research, create follow-up tasks as needed

### References/resources/technical considerations

Sample stage error that says "SSL connection has been closed unexpectedly". You may find additional errors like this if you tail the stage logs directly for a period of time. 

```
2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR [2021-04-26 15:00:18 +0000] [123] [ERROR] Error handling request /v1/names/audit_committees/?q=mike
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     cursor, statement, parameters, context
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     cursor.execute(statement, parameters)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR psycopg2.errors.AdminShutdown: terminating connection due to administrator command
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR SSL connection has been closed unexpectedly
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR The above exception was the direct cause of the following exception:
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_restful/__init__.py", line 266, in error_router
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return self.handle_error(e)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     rv = self.dispatch_request()
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return self.view_functions[rule.endpoint](**req.view_args)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     resp = resource(*args, **kwargs)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask/views.py", line 89, in view
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return self.dispatch_request(*args, **kwargs)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     resp = meth(*args, **kwargs)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_apispec/annotations.py", line 118, in wrapped
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return wrapper(*args, **kwargs)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_apispec/wrapper.py", line 29, in __call__
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     response = self.call_view(*args, **kwargs)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask_apispec/wrapper.py", line 48, in call_view
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return self.func(*args, **kwargs)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/app/webservices/resources/audit.py", line 193, in get
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return {'results': query.all()}
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3346, in all
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return list(self)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return self._execute_and_instances(context)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     result = conn.execute(querycontext.statement, self._params)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return meth(self, multiparams, params)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return connection._execute_clauseelement(self, multiparams, params)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     distilled_params,
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     e, statement, parameters, cursor, context
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     raise exception
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     cursor, statement, parameters, context
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     cursor.execute(statement, parameters)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR SSL connection has been closed unexpectedly
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR [SQL: SELECT ofec_committee_fulltext_audit_mv.idx AS ofec_committee_fulltext_audit_mv_idx, ofec_committee_fulltext_audit_mv.id AS ofec_committee_fulltext_audit_mv_id, ofec_committee_fulltext_audit_mv.name AS ofec_committee_fulltext_audit_mv_name, ofec_committee_fulltext_audit_mv.fulltxt AS ofec_committee_fulltext_audit_mv_fulltxt 
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR FROM ofec_committee_fulltext_audit_mv 
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR WHERE ofec_committee_fulltext_audit_mv.fulltxt @@ to_tsquery(%(fulltxt_1)s) ORDER BY ofec_committee_fulltext_audit_mv.id DESC 
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR  LIMIT %(param_1)s]
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR [parameters: {'fulltxt_1': 'mike:*', 'param_1': 20}]
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR (Background on this error at: http://sqlalche.me/e/13/e3q8)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR During handling of the above exception, another exception occurred:
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     self.handle_request(listener_name, req, client, addr)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     addr)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     respiter = self.wsgi(environ, resp.start_response)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return self.wsgi_app(environ, start_response)
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
   2021-04-26T11:00:18.78-0400 [APP/PROC/WEB/0] ERR     return self.app(environ, start_response)
```

**Comment by lbeaufort** [comment]
It looks like possibly the `terminate_backend` task is terminating connections that have been open for 9 minutes waiting for queries, then the application tries to sends a query to that connection pool and the connection has been closed. I'm going to experiment with the [`pool_recycle` setting](https://docs.sqlalchemy.org/en/14/core/pooling.html) to not use connections that have been open more than 9 minutes.

**Comment by lbeaufort** [comment]
- [ ] Test `pool_recycle` set to 9 minutes - if performance is acceptable, this should work 
- [ ] Alternately, exclude `ROLLBACK` from terminated tasks

**Comment by lbeaufort** [comment]
It looks like connections are a lot higher with this setting (~20 vs ~4 with the normal usage, but max connections on the database are super high, so I think that's fine. We'll be opening up more new connections, but I think that's not inherently an issue because the max connections are [much higher](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Managing.html#AuroraPostgreSQL.Managing.MaxConnections), ex 5,000 for `db.r4.2xlarge` in stage and `r4.8xlarge` in `prod`.

**Comment by lbeaufort** [comment]
Based on Locust testing, it looks like limiting the `pool_recycle` time has a potentially negative impact on performance. I asked @dzhang-fec to exclude the idle `ROLLBACK` connections from the terminate script and tested in `stage`, and it eliminated the errors. Performance testing seems to indicate this won't have a negative impact. After testing, my recommendation is to remove these idle `ROLLBACK` transactions from the termination script in `production as well`. 

New script: 

```sql
SELECT pg_terminate_backend(pid) 
FROM pg_stat_activity 
WHERE  (lower(query) like '%select count(*) as count_1%' or lower(query) like '% limit %' or lower(query) like '%limit%') 
and  lower(query) not like '%rollback%' 
and datname <>'rdsadmin' 
and usename ='fec_api' 
and  (now() - pg_stat_activity.query_start) > interval '9 minutes' 
order by pg_stat_activity.query_start desc
```

To close this issue:
- [ ] Verify the change has been implemented in `prod`
- [ ] Verify the "SSL connection closed" errors no longer in production
- [ ] Check if this script runs on `dev`, keep them consistent

**Comment by lbeaufort** [comment]
Thank you @dzhang-fec for making the change in the dev/stage/prod databases!
